//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comparer.CompWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CompWebService.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Comparer.CompWebService.HelloWorldResponse HelloWorld(Comparer.CompWebService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Comparer.CompWebService.HelloWorldResponse> HelloWorldAsync(Comparer.CompWebService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/test", ReplyAction="*")]
        void test();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/test", ReplyAction="*")]
        System.Threading.Tasks.Task testAsync();
        
        // CODEGEN: Generating message contract since element name ProductListResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProductList", ReplyAction="*")]
        Comparer.CompWebService.ProductListResponse ProductList(Comparer.CompWebService.ProductListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProductList", ReplyAction="*")]
        System.Threading.Tasks.Task<Comparer.CompWebService.ProductListResponse> ProductListAsync(Comparer.CompWebService.ProductListRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddNewProductToDatabase", ReplyAction="*")]
        Comparer.CompWebService.AddNewProductToDatabaseResponse AddNewProductToDatabase(Comparer.CompWebService.AddNewProductToDatabaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddNewProductToDatabase", ReplyAction="*")]
        System.Threading.Tasks.Task<Comparer.CompWebService.AddNewProductToDatabaseResponse> AddNewProductToDatabaseAsync(Comparer.CompWebService.AddNewProductToDatabaseRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Comparer.CompWebService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Comparer.CompWebService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Comparer.CompWebService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Comparer.CompWebService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProductListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProductList", Namespace="http://tempuri.org/", Order=0)]
        public Comparer.CompWebService.ProductListRequestBody Body;
        
        public ProductListRequest() {
        }
        
        public ProductListRequest(Comparer.CompWebService.ProductListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ProductListRequestBody {
        
        public ProductListRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProductListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProductListResponse", Namespace="http://tempuri.org/", Order=0)]
        public Comparer.CompWebService.ProductListResponseBody Body;
        
        public ProductListResponse() {
        }
        
        public ProductListResponse(Comparer.CompWebService.ProductListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ProductListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ProductListResult;
        
        public ProductListResponseBody() {
        }
        
        public ProductListResponseBody(string ProductListResult) {
            this.ProductListResult = ProductListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddNewProductToDatabaseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddNewProductToDatabase", Namespace="http://tempuri.org/", Order=0)]
        public Comparer.CompWebService.AddNewProductToDatabaseRequestBody Body;
        
        public AddNewProductToDatabaseRequest() {
        }
        
        public AddNewProductToDatabaseRequest(Comparer.CompWebService.AddNewProductToDatabaseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddNewProductToDatabaseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public float price;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string date;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string shop;
        
        public AddNewProductToDatabaseRequestBody() {
        }
        
        public AddNewProductToDatabaseRequestBody(string name, float price, string date, string shop) {
            this.name = name;
            this.price = price;
            this.date = date;
            this.shop = shop;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddNewProductToDatabaseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddNewProductToDatabaseResponse", Namespace="http://tempuri.org/", Order=0)]
        public Comparer.CompWebService.AddNewProductToDatabaseResponseBody Body;
        
        public AddNewProductToDatabaseResponse() {
        }
        
        public AddNewProductToDatabaseResponse(Comparer.CompWebService.AddNewProductToDatabaseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddNewProductToDatabaseResponseBody {
        
        public AddNewProductToDatabaseResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : Comparer.CompWebService.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<Comparer.CompWebService.WebServiceSoap>, Comparer.CompWebService.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Comparer.CompWebService.HelloWorldResponse Comparer.CompWebService.WebServiceSoap.HelloWorld(Comparer.CompWebService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Comparer.CompWebService.HelloWorldRequest inValue = new Comparer.CompWebService.HelloWorldRequest();
            inValue.Body = new Comparer.CompWebService.HelloWorldRequestBody();
            Comparer.CompWebService.HelloWorldResponse retVal = ((Comparer.CompWebService.WebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Comparer.CompWebService.HelloWorldResponse> Comparer.CompWebService.WebServiceSoap.HelloWorldAsync(Comparer.CompWebService.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Comparer.CompWebService.HelloWorldResponse> HelloWorldAsync() {
            Comparer.CompWebService.HelloWorldRequest inValue = new Comparer.CompWebService.HelloWorldRequest();
            inValue.Body = new Comparer.CompWebService.HelloWorldRequestBody();
            return ((Comparer.CompWebService.WebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        public void test() {
            base.Channel.test();
        }
        
        public System.Threading.Tasks.Task testAsync() {
            return base.Channel.testAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Comparer.CompWebService.ProductListResponse Comparer.CompWebService.WebServiceSoap.ProductList(Comparer.CompWebService.ProductListRequest request) {
            return base.Channel.ProductList(request);
        }
        
        public string ProductList() {
            Comparer.CompWebService.ProductListRequest inValue = new Comparer.CompWebService.ProductListRequest();
            inValue.Body = new Comparer.CompWebService.ProductListRequestBody();
            Comparer.CompWebService.ProductListResponse retVal = ((Comparer.CompWebService.WebServiceSoap)(this)).ProductList(inValue);
            return retVal.Body.ProductListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Comparer.CompWebService.ProductListResponse> Comparer.CompWebService.WebServiceSoap.ProductListAsync(Comparer.CompWebService.ProductListRequest request) {
            return base.Channel.ProductListAsync(request);
        }
        
        public System.Threading.Tasks.Task<Comparer.CompWebService.ProductListResponse> ProductListAsync() {
            Comparer.CompWebService.ProductListRequest inValue = new Comparer.CompWebService.ProductListRequest();
            inValue.Body = new Comparer.CompWebService.ProductListRequestBody();
            return ((Comparer.CompWebService.WebServiceSoap)(this)).ProductListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Comparer.CompWebService.AddNewProductToDatabaseResponse Comparer.CompWebService.WebServiceSoap.AddNewProductToDatabase(Comparer.CompWebService.AddNewProductToDatabaseRequest request) {
            return base.Channel.AddNewProductToDatabase(request);
        }
        
        public void AddNewProductToDatabase(string name, float price, string date, string shop) {
            Comparer.CompWebService.AddNewProductToDatabaseRequest inValue = new Comparer.CompWebService.AddNewProductToDatabaseRequest();
            inValue.Body = new Comparer.CompWebService.AddNewProductToDatabaseRequestBody();
            inValue.Body.name = name;
            inValue.Body.price = price;
            inValue.Body.date = date;
            inValue.Body.shop = shop;
            Comparer.CompWebService.AddNewProductToDatabaseResponse retVal = ((Comparer.CompWebService.WebServiceSoap)(this)).AddNewProductToDatabase(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Comparer.CompWebService.AddNewProductToDatabaseResponse> Comparer.CompWebService.WebServiceSoap.AddNewProductToDatabaseAsync(Comparer.CompWebService.AddNewProductToDatabaseRequest request) {
            return base.Channel.AddNewProductToDatabaseAsync(request);
        }
        
        public System.Threading.Tasks.Task<Comparer.CompWebService.AddNewProductToDatabaseResponse> AddNewProductToDatabaseAsync(string name, float price, string date, string shop) {
            Comparer.CompWebService.AddNewProductToDatabaseRequest inValue = new Comparer.CompWebService.AddNewProductToDatabaseRequest();
            inValue.Body = new Comparer.CompWebService.AddNewProductToDatabaseRequestBody();
            inValue.Body.name = name;
            inValue.Body.price = price;
            inValue.Body.date = date;
            inValue.Body.shop = shop;
            return ((Comparer.CompWebService.WebServiceSoap)(this)).AddNewProductToDatabaseAsync(inValue);
        }
    }
}
